# Use Cleanstart Python image
FROM python:3.11

WORKDIR /app

# Copy project files
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Expose app1 port
EXPOSE 5000

# Run app2.py
CMD ["python", "app1.py"]
