# Dockerfile.v1
FROM nginx:latest

WORKDIR /app

# Optional custom nginx config
# COPY nginx.conf ./  

# Copy website files
COPY ../html1 /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Run nginx in foreground
CMD ["nginx", "-g", "daemon off;"]
