# Use the official NGINX image
FROM cleanstart/nginx:latest-dev

# Copy a local file to the default NGINX web directory in the container
COPY index.html /usr/share/nginx/html/index.html

# Expose port 80 to the host machine
EXPOSE 80