FROM cleanstart/python:latest-dev

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

# override the default Entrypoint
CMD ["app1.py"]
