# Start with the official Python base image
FROM python:3.11

WORKDIR /app1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app1.py .

EXPOSE 5000

CMD ["python", "app1.py"]
